# Generated by Django 4.2.3 on 2023-07-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_klient_doktor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='doktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.doktor'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='xona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.xona'),
        ),
    ]
