# Generated by Django 4.2.3 on 2023-07-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_klient_doktor_alter_klient_xona'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
