# Generated by Django 4.2.3 on 2023-07-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_klient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xona',
            name='status',
        ),
    ]
