# Generated by Django 4.2.3 on 2023-07-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_xona_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='xona',
            name='narxi',
            field=models.IntegerField(default=0, verbose_name='Narxi USD'),
        ),
    ]
