# Generated by Django 4.2.3 on 2023-07-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_xona_narxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='xamshira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.xamshira'),
        ),
    ]
